I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 94, in script
    creepy_man "Hey, beautiful. How about a dance?"
Exception: Sayer 'creepy_man' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 94, in script
    creepy_man "Hey, beautiful. How about a dance?"
  File "C:\Users\Jaque\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jaque\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'creepy_man' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Yona Of The Dawn 1.0
Thu Nov 16 15:17:35 2023
